#!/bin/bash

if [ ! -p /tmp/homegroup ]
then
    echo "HomeGroup not running"
    exit 1
fi


if [ $# == 0 ]
then

    echo "BROWSE" > /tmp/homegroup
    
    cat /tmp/homegroup

else

    echo "CONNECT $1" > /tmp/homegroup
    
    ANS=`cat /tmp/homegroup`
    
    if [ "$ANS" == "None" ]
    then
        echo "Server not found"
        exit 0
    fi
    
    
    declare -a VALS
    i=0
    for a in $ANS
    do
        VALS[i]=$a
        i=($i+1)
    done
    
    smbclient -L //${VALS[0]} --user ${VALS[1]}%${VALS[2]}
    
fi